### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by wedneyyuri** [Creditas/vanilla-masker#103]
The last version currently available in npm is `1.0.9`. 

We are missing the commit https://github.com/BankFacil/vanilla-masker/commit/25823bb4565ba15fb88f57398182899c5b1910d7, it should improve significantly our installation time (phantomjs download).

**Comment by estevaoam** [comment]
:+1

**Comment by QuentinFchx** [comment]
@renato-zannon is this library still maintained ?

**Comment by joshgillies** [comment]
yeah would love to get this: #70 released...

**Comment by QuentinFchx** [comment]
Ping @valtermartins1301 @leoandreucci. Is your organization still maintaining this project?
If not could you transfer the ownership to anyone?

**Comment by rmanenti** [comment]
It's quite hard to find a good mask plugin. I really like this one, but without maintenance it will be hard to keep using it in the future. Is there any plugin that is similar to this one and is constantly updated?

**Comment by leoandreucci** [comment]
Hi everyone, I´m very sorry for the lack of response regarding the Vanilla Masker project. We´ve had some changes in our company and haven´t been able to keep up with it.

We are growing our team again and intend to better manage the project in the future, but in the meantime we´ve granted @QuentinFchx write permissions to approve PRs and help with it

Thanks again @QuentinFchx for the support!

**Comment by wedneyyuri** [comment]
Hi @leoandreucci,

what about the npm publish permission?

**Comment by QuentinFchx** [comment]
I'll discuss issues regarding npm publishing with the original maintainers.

Do not hesitate to open issues around anything you'd like to see implemented.
Ideas:
- Typescript support (rewrite in ts or just add type definitions?)
- GH page improvement
- ...

I'll take a look at opened issues/pr starting tomorrow 😄

**Comment by QuentinFchx** [comment]
I just released vanilla-masker@1.1.1 on npm.
Does that fix the issue for you ?
