### ISSUE TITLE
problem using in windows

### ISSUE THREAD

**Issue by vakopian** [Creditas/vanilla-masker#75]
This project has a directory called `bankfacil:vanilla-masker` which contains the `:` character which is not a legal character for a windows directory. This causes problems in windows. Doing a simple `git clone` of this repo in windows fails. Similarly when npm tries to unpack this module, it also fails under windows. Is there a way to rename the `bankfacil:vanilla-masker` directory to something without special characters?

**Comment by Dadidam** [comment]
I have same problem on Windows. **npm** has no reaction and warnings (when install module), and before I find this issue, I don't understand what's going on.

**Comment by phammers** [comment]
I have the same issue - it happens with bower as well.

**Comment by fritteli** [comment]
Same here. We're using Windows at work, and we're unable to use this module. Any chance you can do somehting about it? Soon? :)

**Comment by jpmsegurado** [comment]
Same issue here, looking forward to any updates :)

**Comment by jpmsegurado** [comment]
try using this link https://github.com/Futuring/vanilla-masker I removed the folder which gives the error, it will work, except for meteor :)

**Comment by fnfilho** [comment]
+1
I see there is a PR for this issue already. Can It be deployed?

**Comment by QuentinFchx** [comment]
Tracking in #91
